# Array (Numeric) functions
# basic functions:
- np.array([],dtype='int')
- np.random.randint(l,h,count)
- np.arange(l,h,step,dtype)
- arr.reshape([n,m])
- np.empty(n,dtype='')
- np.zeros(n,dtype='')
- np.ones(n,dtype='')
- np.fromiter(iterable,dtype='',count=-1)
- np.linspace(l,h,num_count,dtype)
- np.logspace(l,h,count,base)

# Slicing
- slice(start, stop, step)
- np.s_[] # example - a[np.s_[::3]], a[np.s_[5:7]] (7 is not included-[5,6])

# Conditions
- arr[condition]
- np.isnan(arr)
- np.iscomplex(arr)

# iterator object 
- np.nditer(arr) 

# transpose
- a.T
- arr.transpose()

# Joining Arrays
- np.concatenate((a,b),axis)
- np.stack((a,b),axis)
- np.hstack((a,b))
- np.vstack((a,b))

# Splitting Arrays
- np.split(a,m)  # for 1d aray, m=Count of equal splits (3) or m = list of indexes to split from [2,4,7]
- np.hsplit(a,m) # for 2 d array, horizontal split from m row
- np.vsplit(a,m)  # for 2d array, vertical split from m column

# Adding / Removing Elements
- np.resize(a,n) # n can be integer to reduce or increase array size or tuple (n,m) to resize matrix
- np.append(arr,[],axis)
- np.insert(arr,pos, [],axis)
- no.delete(a,pos,axis)
- np.unique(a,return_index=True,return_inverse=True,return_counts=True)


# array creation and basic functions

In [17]:
import numpy as np
a=np.array(np.random.randint(1,5000,5))
print(a.shape),a

(5,)


(None, array([3974, 3192, 2126, 2998, 3251]))

In [24]:
# 2 dim Array
aa=np.array([np.random.randint(1,5000,5),np.random.randint(1,1000,5)])
aa.shape,aa

((2, 5),
 array([[4317, 1485, 2526, 4940, 4777],
        [ 280,  622,   98,  923,  920]]))

In [26]:
aa.reshape(5,2)

array([[4317, 1485],
       [2526, 4940],
       [4777,  280],
       [ 622,   98],
       [ 923,  920]])

In [33]:
# length of each element
print(aa.itemsize)
ab=np.array([('name','kjhgvc')])
print(ab.itemsize)
ab=np.array([1.2,2.3])
print(ab.itemsize)

4
24
8


In [48]:
np.empty(5,dtype='int')
#The elements in an array show random garbage values as they are not initialized.

array([1898948208,        425,          0,          0,          1])

In [47]:
np.zeros(5,dtype='int'),np.zeros(5,dtype='str'),np.zeros(5,dtype='double')

(array([0, 0, 0, 0, 0]),
 array(['', '', '', '', ''], dtype='<U1'),
 array([0., 0., 0., 0., 0.]))

In [46]:
np.ones(5,dtype='int'),np.ones(5,dtype='str'),np.ones(5,dtype='float')

(array([1, 1, 1, 1, 1]),
 array(['1', '1', '1', '1', '1'], dtype='<U1'),
 array([1., 1., 1., 1., 1.]))

In [45]:
# same as np.array with less params
a=[1,3,4,5,6,6]
np.asarray(a,dtype='str'),np.asarray(a,dtype='int'),np.asarray(a,dtype='double')

(array(['1', '3', '4', '5', '6', '6'], dtype='<U1'),
 array([1, 3, 4, 5, 6, 6]),
 array([1., 3., 4., 5., 6., 6.]))

In [57]:
# returns n-dim array from any iterable. Below code returns np array from list. count=-1 == read all data
np.fromiter([8,5,2,8,0,8,9],dtype='int',count=-1)

array([8, 5, 2, 8, 0, 8, 9])

In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.arange(0,1000,30,dtype='float')

array([  0.,  30.,  60.,  90., 120., 150., 180., 210., 240., 270., 300.,
       330., 360., 390., 420., 450., 480., 510., 540., 570., 600., 630.,
       660., 690., 720., 750., 780., 810., 840., 870., 900., 930., 960.,
       990.])

In [69]:
# same as arange but evenly spaces values
np.linspace(0,50,5,dtype='float'),np.linspace(0,50,5,dtype='float',endpoint = False)

(array([ 0. , 12.5, 25. , 37.5, 50. ]), array([ 0., 10., 20., 30., 40.]))

In [73]:
print(np.logspace(1,10,num=10,base=2))
# 10   base^1
# 10   base^10
# num  count of numbers to print
# base log base
print(np.logspace(1,2,num=10,base=10))

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]
[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


# Array slice

In [238]:
# slice pt 1
a=np.random.randint(1,100,5)
s=slice(2,50,2) #start, stop, and step
print(a,s,a[s])
# slice pt 2
print(a[0],a[1:],a[2:4])
print(np.array([[1,2,3],[2,3,4],[3,4,2]])[1:])
# Slicing can also include ellipsis (…) to make a selection tuple of the same length as the dimension of an array. 
# If ellipsis is used at the row position, it will return an ndarray comprising of items in rows.
a=np.array([[1,2,3],[2,3,4],[3,4,2]])
print('1st row : ', a[...,0],'\n2nd row : ',a[...,1],'\n3rd row : ',a[...,2])
print(a[...,1:])
print(a[1:2,2:3])
a=np.arange(10)
print(a)
print("Sliced a ",a[np.s_[::3]])

[80 18 87 22 59] slice(2, 50, 2) [87 59]
80 [18 87 22 59] [87 22]
[[2 3 4]
 [3 4 2]]
1st row :  [1 2 3] 
2nd row :  [2 3 4] 
3rd row :  [3 4 2]
[[2 3]
 [3 4]
 [4 2]]
[[4]]
[0 1 2 3 4 5 6 7 8 9]
Sliced a  [0 3 6 9]


In [99]:
a=np.random.randint(1,100,20)
a,a[a>50]

(array([49, 64, 79, 74, 37,  2, 23, 83, 45, 10, 16, 19, 98, 83, 84, 87, 90,
        10, 98, 24]),
 array([64, 79, 74, 83, 98, 83, 84, 87, 90, 98]))

In [103]:
a=np.array([np.nan,1,np.nan,2,np.nan,3])
a[~np.isnan(a)],a[np.isnan(a)]

(array([1., 2., 3.]), array([nan, nan, nan]))

In [104]:
a=np.array([1+6j,2+9j,2,3])
a[np.iscomplex(a)],a[~np.iscomplex(a)]

(array([1.+6.j, 2.+9.j]), array([2.+0.j, 3.+0.j]))

# Broadcasting

In [108]:
a=np.array([1,2,3,4])
b=np.array([10,20,30,40])
a*b,a+b,a-b,a/b

(array([ 10,  40,  90, 160]),
 array([11, 22, 33, 44]),
 array([ -9, -18, -27, -36]),
 array([0.1, 0.1, 0.1, 0.1]))

# iterator object 

In [110]:
a=np.arange(0,100,20)
for i in np.nditer(a):
    print(i)

0
20
40
60
80


In [122]:
a=np.arange(0,100,2)
a.reshape(25,2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [129]:
for i,j in np.nditer([a,np.arange(len(a))]):
    print(i,":",j)

0 : 0
2 : 1
4 : 2
6 : 3
8 : 4
10 : 5
12 : 6
14 : 7
16 : 8
18 : 9
20 : 10
22 : 11
24 : 12
26 : 13
28 : 14
30 : 15
32 : 16
34 : 17
36 : 18
38 : 19
40 : 20
42 : 21
44 : 22
46 : 23
48 : 24
50 : 25
52 : 26
54 : 27
56 : 28
58 : 29
60 : 30
62 : 31
64 : 32
66 : 33
68 : 34
70 : 35
72 : 36
74 : 37
76 : 38
78 : 39
80 : 40
82 : 41
84 : 42
86 : 43
88 : 44
90 : 45
92 : 46
94 : 47
96 : 48
98 : 49


# array changing shape:

In [148]:
a=np.arange(1,10,1)
a=a.reshape(3,3)
print(a)
print(a.flat,[i for i in a.flat])
print(a.flatten())
print(np.array([1,2,7,9,5]).ravel())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<numpy.flatiter object at 0x000001A9724008A0> [1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 2 3 4 5 6 7 8 9]
[1 2 7 9 5]


# transpose
- a.T
- arr.transpose()

In [161]:
# Transpose Operations
print(a)
print(a.transpose())
print(a.T)
a=np.array([a[...,1],a[...,0],a[...,2]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[2 5 8]
 [1 4 7]
 [3 6 9]]


# Joining Arrays
- np.concatenate((a,b),axis)
- np.stack((a,b),axis)
- np.hstack((a,b))
- np.vstack((a,b))

In [178]:
# Joining arrays pt-1 : 
a=np.arange(1,10,1)
a=a.reshape(3,3)
print(a)
print(a+[1,1,1])
print(np.concatenate((a,a.T))) # parentheses are imp
print('row concatenation : \n',np.concatenate((a,a.T),axis=0)) # 
print('Column concatenation :\n',np.concatenate((a,a.T),axis=1)) # 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 4 7]
 [2 5 8]
 [3 6 9]]
row concatenation : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 4 7]
 [2 5 8]
 [3 6 9]]
Column concatenation :
 [[1 2 3 1 4 7]
 [4 5 6 2 5 8]
 [7 8 9 3 6 9]]


In [184]:
# Joining arrays pt-2 : 
# stack function - This function joins the sequence of arrays along a new axis. 
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[3,4]])
print('stack axis - 0 : \n',np.stack((a,b),axis=0))
print('stack axis - 1 : \n',np.stack((a,b),axis=1))
# Variants of numpy.stack function to stack so as to make a single array horizontally/vertically.
print('hstack : \n',np.hstack((a,b)))
print('vstack : \n',np.vstack((a,b)))

stack axis - 0 : 
 [[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]
stack axis - 1 : 
 [[[1 2]
  [1 2]]

 [[3 4]
  [3 4]]]
hstack : 
 [[1 2 1 2]
 [3 4 3 4]]
vstack : 
 [[1 2]
 [3 4]
 [1 2]
 [3 4]]


# Splitting Arrays
- np.split(a,m)  # for 1d aray, m=Count of equal splits (3) or m = list of indexes to split from [2,4,7]
- np.hsplit(a,m) # for 2 d array, horizontal split from m row
- np.vsplit(a,m)  # for 2d array, vertical split from m column

In [198]:
# Spliting arrays : split, hsplit, vsplit
a=np.arange(9)
print('Array : ', a)
print('Split the array in 3 equal-sized subarrays : ',np.split(a,3))
print('Split the array in given indexes 4 and 7 : ',np.split(a,[4,7])) 
print('Split the array in given indexes 2, 4, 6 and 8 : ',np.split(a,[2,4,6,8])) 
# hsplit, vsplit
a=np.arange(16).reshape(4,4)
print('Array : ',a)
print('hsplit : \n',np.hsplit(a,2))
print('vsplit : \n',np.vsplit(a,2))

Array :  [0 1 2 3 4 5 6 7 8]
Split the array in 3 equal-sized subarrays :  [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
Split the array in given indexes 4 and 7 :  [array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]
Split the array in given indexes 2, 4, 6 and 8 :  [array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8])]
Array :  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
hsplit : 
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
vsplit : 
 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


# Adding / Removing Elements
- np.resize(a,n) # n can be integer to reduce or increase array size or tuple (n,m) to resize matrix
- np.append(arr,[],axis)
- np.insert(arr,pos, [],axis)
- no.delete(a,pos,axis)
- np.unique(a,return_index=True,return_inverse=True,return_counts=True)


In [255]:
# resize: returns a new array with the specified size.If the new size is greater than the original, the repeated copies of entries in the original are contained
a=np.arange(5)
print('a=',a)
print('resizing to lesser size : ',np.resize(a,3))
print('resizing to larger size : ',np.resize(a,8))
a=np.array([[1,2,3],[1,2,3]])
print('a=',a)
print('matrix resize : ', np.resize(a,(3,2)))
print('append 1d array : ',np.append(a,np.arange(3)))
print('a=',a)
print('append 2d array axis=0 : ',np.append(a,[[3,4,5]],axis=0))
print('append 2d array axis=1 : ',np.append(a,[[3],[4]],axis=1))

print('Insertion - ')
#function inserts values in the input array along the given axis and before the given index. 
# If the type of values is converted to be inserted, it is different from the input array. 
# Insertion is not done in place and the function returns a new array. Also, if the axis is not mentioned, 
# the input array is flattened.
a=np.arange(10).reshape(2,5)
print('a=',a)
print('insert 3rd row : ', np.insert(a,2,[1,2,3,4,5])) # no axis flattens the array
print('insert 3rd row : ', np.insert(a,0,[1,2,3,4,5],axis=0)) # axis appends to given axis at given place
a=np.insert(a,0,[[1,2,3,7,8]],axis=0)
print('a=',a)
print('Delete - ')
print('Delete first row from axis 0 in 2d array : ',np.delete(a,0,axis=0))
a=np.arange(10)
print('a=',a)
print('Delete 7th element from 1d array : ', np.delete(a,7))
print('Delete the slices : ', np.delete(a,np.s_[::2]))
print('Unique : ')
a=np.array([1,2,2,1,1,3,1,2,2,3])
# very important
print("a=",a)
print('Unique array from a: ',np.unique(a))
b,ind=np.unique(a,return_index=True)
print('Unique return indexes (2nd array is index) : ', b,ind)
b,ind,inv=np.unique(a,return_index=True,return_inverse=True)
print('Unique return index, return inverse : ',b,ind,inv)
# If True, returns the indices of unique array, which can be used to reconstruct the input array
b,ind,inv,cnt=np.unique(a,return_index=True,return_inverse=True,return_counts=True)
print('Unique, return_index, return_inverse return_count : ',b,ind,inv,cnt)

a= [0 1 2 3 4]
resizing to lesser size :  [0 1 2]
resizing to larger size :  [0 1 2 3 4 0 1 2]
a= [[1 2 3]
 [1 2 3]]
matrix resize :  [[1 2]
 [3 1]
 [2 3]]
append 1d array :  [1 2 3 1 2 3 0 1 2]
a= [[1 2 3]
 [1 2 3]]
append 2d array axis=0 :  [[1 2 3]
 [1 2 3]
 [3 4 5]]
append 2d array axis=1 :  [[1 2 3 3]
 [1 2 3 4]]
Insertion - 
a= [[0 1 2 3 4]
 [5 6 7 8 9]]
insert 3rd row :  [0 1 1 2 3 4 5 2 3 4 5 6 7 8 9]
insert 3rd row :  [[1 2 3 4 5]
 [0 1 2 3 4]
 [5 6 7 8 9]]
a= [[1 2 3 7 8]
 [0 1 2 3 4]
 [5 6 7 8 9]]
Delete - 
Delete first row from axis 0 in 2d array :  [[0 1 2 3 4]
 [5 6 7 8 9]]
a= [0 1 2 3 4 5 6 7 8 9]
Delete 7th element from 1d array :  [0 1 2 3 4 5 6 8 9]
Delete the slices :  [1 3 5 7 9]
Unique : 
a= [1 2 2 1 1 3 1 2 2 3]
Unique array from a:  [1 2 3]
Unique return indexes (2nd array is index) :  [1 2 3] [0 1 5]
Unique return index, return inverse :  [1 2 3] [0 1 5] [0 1 1 0 0 2 0 1 1 2]
Unique, return_index, return_inverse return_count :  [1 2 3] [0 1 5] [0 1 1 0 0 2 0 1 1

In [257]:
a='(()))))(((())))))'
b=np.array(list(a))
print(b)
np.unique(b,return_index=True,return_inverse=True,return_counts=True)

['(' '(' ')' ')' ')' ')' ')' '(' '(' '(' '(' ')' ')' ')' ')' ')' ')']


(array(['(', ')'], dtype='<U1'),
 array([0, 2], dtype=int64),
 array([0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1], dtype=int64),
 array([ 6, 11], dtype=int64))